---
abstract: 'Provides an LDAP model bound as the user who logged in.'
author:
  - 'Tomas Doran (t0m) C<< <bobtfish@bobtfish.net >>'
build_requires:
  Catalyst::Runtime: 0
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.99'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Model-LDAP-FromAuthentication
no_index:
  directory:
    - inc
    - t
requires:
  Catalyst::Authentication::Store::LDAP: 0.1004
  Catalyst::Component::InstancePerContext: 0
  Catalyst::Model::LDAP: 0.16
  Moose: 0
  MooseX::Types::Common::String: 0
  MooseX::Types::LoadableClass: 0.005
  namespace::autoclean: 0
  perl: 5.005003
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/bobtfish/catalyst-model-ldap-fromauthentication.git
version: 0.02
